# Generated by Django 2.1.7 on 2019-03-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=128)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
